-- 코드를 입력하세요
SELECT b.AUTHOR_ID,AUTHOR_NAME,CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK b JOIN AUTHOR a on b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES s on b.BOOK_ID = s.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID,CATEGORY desc