-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(o.USER_ID)) AS PUCHASED_USERS, 
round(COUNT(DISTINCT(o.USER_ID))/(SELECT count(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
FROM USER_INFO u JOIN ONLINE_SALE o on u.USER_ID = o.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH
