SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID NOT IN (
    SELECT B.ITEM_ID
    FROM ITEM_TREE A JOIN ITEM_TREE B ON A.PARENT_ITEM_ID = B.ITEM_ID	
    WHERE A.PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC