SELECT ID, 
    CASE WHEN LANKING <= 0.25 THEN 'CRITICAL'
    WHEN LANKING <= 0.5 THEN 'HIGH'
    WHEN LANKING <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS LANKING
     FROM ECOLI_DATA) T
ORDER BY ID