-- 코드를 입력하세요
SELECT i.REST_ID,i.REST_NAME,i.FOOD_TYPE,i.FAVORITES,i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE),2) as REVIEW_SCORE
from REST_INFO i join REST_REVIEW r on i.REST_ID = r.REST_ID
where i.ADDRESS like '서울%'
group by i.REST_ID
order by REVIEW_SCORE desc, FAVORITES desc