-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER,COUNT(distinct(o.USER_ID)) AS USERS
FROM ONLINE_SALE o left join USER_INFO i on o.USER_ID=i.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR,MONTH,GENDER
