-- 코드를 입력하세요
SELECT USER_ID,NICKNAME,SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B LEFT JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE STATUS ='DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES