WITH RECURSIVE T1 AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ED2.ID, ED2.PARENT_ID, GENERATION + 1
    FROM T1 ED1 JOIN ECOLI_DATA ED2 ON ED1.ID = ED2.PARENT_ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM T1
WHERE ID NOT IN (SELECT DISTINCT(PARENT_ID) FROM T1 WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION