WITH RECURSIVE T1 AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ED.ID, ED.PARENT_ID, T.GENERATION + 1
    FROM T1 T JOIN ECOLI_DATA ED ON T.ID = ED.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM T1
WHERE ID NOT IN (SELECT PARENT_ID FROM T1 WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION