WITH RECURSIVE TMP AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT D.ID, D.PARENT_ID, T.GENERATION + 1
    FROM TMP T JOIN ECOLI_DATA D ON T.ID = D.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM TMP
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM TMP WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION