-- 코드를 입력하세요
SELECT B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK B LEFT JOIN AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID 
LEFT JOIN BOOK_SALES S ON B.BOOK_ID	=S.BOOK_ID	
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID,CATEGORY DESC