-- 코드를 입력하세요
SELECT o.PRODUCT_ID, PRODUCT_NAME, sum(PRICE*AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT p join FOOD_ORDER o on p.PRODUCT_ID = o.PRODUCT_ID
where date_format(PRODUCE_DATE,'%Y-%m') = '2022-05'
group by PRODUCT_ID
order by TOTAL_SALES desc, PRODUCT_ID
