-- 코드를 입력하세요
SELECT o.PRODUCT_ID,PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p JOIN FOOD_ORDER o on p.PRODUCT_ID=o.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID