SELECT HISTORY_ID, ROUND(SUM(DAILY_FEE * ((100 - DISCOUNT_RATE) / 100) * (DATEDIFF(END_DATE, START_DATE) + 1))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN (
    SELECT *, ( CASE 
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭')
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭')
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭') 
    ELSE 0 END) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) H ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC


