WITH RECURSIVE H AS (
    SELECT 0 AS HOUR
    UNION ALL
	SELECT HOUR + 1 FROM H WHERE HOUR < 23
)


SELECT HOUR, COUNT(DATETIME) AS COUNT
FROM H H LEFT JOIN ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR