WITH RECURSIVE T1 AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM T1
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM T1 T LEFT JOIN ANIMAL_OUTS AO ON HOUR = HOUR(AO.DATETIME)
GROUP BY HOUR
ORDER BY HOUR