-- 코드를 입력하세요
SELECT O.PRODUCT_ID,P.PRODUCT_NAME, SUM(O.AMOUNT*P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P INNER JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
where PRODUCE_DATE like '2022-05%'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID