WITH GRADES AS (
    SELECT CASE 
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C' END AS GRADE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
), BONUSES AS (
    SELECT CASE 
    WHEN GRADE = 'S' THEN SAL * 0.2
    WHEN GRADE = 'A' THEN SAL * 0.15
    WHEN GRADE = 'B' THEN SAL * 0.1
    ELSE 0 END AS BONUS, GRADE, G.EMP_NO, EMP_NAME
    FROM GRADES G JOIN HR_EMPLOYEES HE ON G.EMP_NO = HE.EMP_NO
)

SELECT EMP_NO, EMP_NAME, GRADE, BONUS
FROM BONUSES
ORDER BY EMP_NO