SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM (SELECT MEMBER_ID 
      FROM REST_REVIEW 
      GROUP BY MEMBER_ID
      ORDER BY COUNT(*) DESC
      LIMIT 1
     ) RR JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
     JOIN REST_REVIEW RR2 ON RR2.MEMBER_ID = MP.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT