-- 코드를 작성해주세요
SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T 
JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
JOIN ITEM_INFO P ON T.PARENT_ITEM_ID = P.ITEM_ID
WHERE P.RARITY = 'RARE' 
ORDER BY ITEM_ID DESC