WITH T1 AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAXSIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT T.YEAR, (T.MAXSIZE - D.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM T1 T, ECOLI_DATA D 
WHERE YEAR(DIFFERENTIATION_DATE) = T.YEAR
ORDER BY T.YEAR, YEAR_DEV