SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA ED, (SELECT MAX(SIZE_OF_COLONY) AS SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) T1
WHERE YEAR(ED.DIFFERENTIATION_DATE) = T1.YEAR
ORDER BY YEAR, YEAR_DEV