SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO NI ON FI.FISH_TYPE = NI.FISH_TYPE
WHERE FI.FISH_TYPE IN (SELECT FISH_TYPE 
             FROM FISH_INFO
             GROUP BY FISH_TYPE
             HAVING LENGTH = MAX(LENGTH)
            )
ORDER BY ID            