SELECT SUM(SCORE) AS SCORE, G.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
WHERE YEAR = '2022'
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
