-- 코드를 입력하세요
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR  C LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '세단' AND DATE_FORMAT(START_DATE,'%m') = '10'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC