SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
CASE STATUS WHEN 'DONE' THEN '거래완료'
WHEN 'RESERVED' THEN '예약중'
ELSE '판매중' END AS STATUS
FROM USED_GOODS_BOARD
WHERE DATE_FORMAT(CREATED_DATE, "%Y-%m-%d") = '2022-10-05'
ORDER BY BOARD_ID DESC
