-- 코드를 입력하세요
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE,PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
AND(CATEGORY LIKE '과자' || CATEGORY LIKE '국' ||CATEGORY LIKE '김치' ||CATEGORY LIKE '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC