WITH FRONTEND AS (
    SELECT SUM(CODE) AS FE_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
), T1 AS (
    SELECT
    CASE WHEN SKILL_CODE & FE_CODE AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
    WHEN SKILL_CODE & FE_CODE THEN 'C' END AS GRADE, ID, EMAIL
    FROM DEVELOPERS, FRONTEND
)

SELECT GRADE, ID, EMAIL
FROM T1
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID