WITH FRONT AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
), GRADES AS (
    SELECT ID, EMAIL,
    CASE WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND SKILL_CODE & F.CODE THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
    WHEN SKILL_CODE & F.CODE THEN 'C' END AS GRADE
    FROM DEVELOPERS D, FRONT F
)

SELECT GRADE, ID, EMAIL
FROM GRADES
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID
